name: Build-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform version $(TF-Version)'
  inputs:
    terraformVersion: '$(TF-Version)'
- script: terraform init -get=true -upgrade=true
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
- script: 'terraform validate'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Validate Terraform Code'
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
- script: 'terraform plan'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Dry Run (Plan)'
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
- script: 'terraform apply -auto-approve'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Run (Apply)'
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
- script: 'terraform destroy -auto-approve'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Destroy'
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*
     !.git/**/*
     !.terraform/**/*
     !*.tfstate
     !*.tfstate.*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_jungopro'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '1.$(Build.BuildId).0'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Additional Notes'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'